name: 'Get and Caceh Dependancies'
description: 'Get dependacies using NPM and cache them'
inputs:
  caching:
    description: 'Whether to cache ddependacies or not'
    required: false
    default: 'true'
outputs:
  uses-cache:
    description: 'Whether cache was used or not'
    value: $ {{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != true || input.caching != 'true'
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash